### PR TITLE
chore: 0.3.4+1 : Export type SupabaseRealtimePayload

### PR DESCRIPTION
**Pull request by DanMossa**
It's helpful to specify the type when using subscriptions.

### CODE REVIEW

**Comment by dshukertjr** [comment]
Nice one @DanMossa !

It seems like we are getting some analysis error with it. Could you check it out?

**Comment by DanMossa** [comment]
Bizarre. Tests are failing but I'm unable to get the same error when I run the test locally. Are you also getting failing tests when you run them locally?

**Comment by dshukertjr** [comment]
@DanMossa Actually, the tests have been very flaky lately. I was going to work on a fix at some point, but haven't been able to do so yet. After rerunning it a few times, it usually passes. 

I will rerun the tests and if they pass, I will go ahead and merge this PR!

**Review by dshukertjr — APPROVED** [review]
LGTM! Thanks for the amazing work!

**Pull request merged**
