### PR TITLE
feat: custom http client

### PR DESCRIPTION
**Pull request by Vinzent03**

### CODE REVIEW

**Review by dshukertjr — APPROVED** [review]
Nice! It's all coming together! It looks good to me, but is this good to be merged?

**Comment by Vinzent03** [comment]
@dshukertjr  I'm ready for merging. Next step is `supabase-flutter`

**Comment by dshukertjr** [comment]
@Vinzent03 Nice! In that case, should we release this one as `v1.0.0-dev.2`? Will you be able to update the version number and add it to changelog?

**Comment by Vinzent03** [comment]
Done. In addition, I updated the lint to use the package `lints` like in the other sub libraries since the rework.

**Review by dshukertjr — APPROVED** [review]
@Vinzent03 Amazing! Thank you so much!

**Pull request merged**
