### PR TITLE
feat: make it compatible with the new realtime update

### PR DESCRIPTION
**Pull request by dshukertjr**
This PR brings the new realtime update to supabae-dart
https://github.com/supabase-community/realtime-dart/pull/47

`.stream()` now does not require `.execute()` at the end. Instead, you can just listen to it like the following. Its implementation was heavily inspired by [this](https://github.com/supabase-community/postgrest-dart/pull/69) postgrest-dart implementation!

Also thought is might be easier to separate the filters such as `.eq()` on its own method instead of including it in the `.from()` clause. Realtime team is working on bringing other types of filtering as well. 
```dart
supabase.from('my_table')
  .stream(['id'])
  .eq('title', 'Supabase')
  .order('created_at')
  .limit(100)
  .listen((payload) {
    // do something with payload here
  });
```

One thing I want to discuss is whether we should keep the `.stream()` method or not. I personally like the method, and I think it provides an intuitive way for Dart developers to get started with Supabase's realtime feature. 

However, with the most recent update, supabase-js removed `SupabaseQueryBuilder` class as you can see [here](https://github.com/supabase/supabase-js/blob/rc/src/SupabaseClient.ts). With supabase-js v2, all supabase-js is doing is simply exposing Postgrest or realtime classes and it's not doing a whole lot more. This makes the Dart library deviate quite a bit from the js library.  

I personally think we should keep the `stream()` method, but am open to suggestions/ comments!

### CODE REVIEW

**Comment by dshukertjr** [comment]
I also have to include some upgrade guides on `changelog`.

**Review by bdlukaa — APPROVED** [review]
LGTM

**Comment by Vinzent03** [comment]
I think we definitely should keep `stream`. It's so useful and I think it's the most used use case of realtime. I wonder why supabase-js doesn't have this feature.

**Comment by dshukertjr** [comment]
Cool! Let's keep `stream()` method then!

I will merge this one and do the package update in a separate PR.

**Comment by dshukertjr** [comment]
Also another thing that I forgot to write on the description of this PR: I updated the `pubspec.yaml` file to use a specific version of each sub-libraries like this `realtime_client: 1.0.0-dev.2` without the `^`. 

Since during developer preview, there still might be some breaking changes on each sub-libraries. I didn't want any developers using `supabase_dart` or `supabase_flutter` to receive those breaking changes just because we have released a new version of the sub-libraries. 

supabase-js should be releasing a stable v2.0 soon, so we can then move to releasing supabase-dart v1.0, and can go back to adding `^` within `pubspec.yaml`.

**Pull request merged**
