### PR TITLE
fix: updated version in pubspec.yml to 0.2.15

### PR DESCRIPTION
**Pull request by dshukertjr**
Updated the `version` within pubspec.yaml, which I totally missed in [this PR](https://github.com/supabase-community/supabase-dart/pull/98).

### CODE REVIEW

**Comment by growthondev** [comment]
is this not possible yet?

**Comment by dshukertjr** [comment]
Thanks for asking @growthondev. v0.2.15 is released, but just need this PR to get merged to keep the published package in sync with the code base.

**Comment by growthondev** [comment]
@dshukertjr thanks for the reply.
Is there anyways to get v0.2.15 without using `flutter pub get`?
Cause I couldn't get the v0.2.15 using `flutter pub get`
Thank you

**Comment by DanMossa** [comment]
Oops my bad!
@growthondev
If just changing the version doesn't work, you can always change your pubspec.yaml to

```
dependencies:
  flutter:
    sdk: flutter
  supabase:
    git: git@github.com:supabase-community/supabase-dart.git
```

**Comment by DanMossa** [comment]
Also, @dshukertjr do you think it makes sense to update gotrue to 0.2.0 in this PR as well?

**Review by bdlukaa — APPROVED** [review]

**Comment by dshukertjr** [comment]
@DanMossa Thanks for opening #103 ! I just merged this PR, so you can merge this branch with your PR branch!

**Pull request merged**
